### ISSUE TITLE
VM download links return 404

### ISSUE THREAD

**Issue by davidgengenbach** [onfsdn/atrium-docs#4]
The download links in the [wiki](https://github.com/onfsdn/atrium-docs/wiki) link to 404s, e.g.: 
https://dl.orangedox.com/B1tpLwGGhLc9dauq27

Are there alternative links?

**Comment by charlesmcchan** [comment]
As described in the same wiki page, Atrium project has been archived and all the efforts have been transferred to another project: Trellis. https://www.opennetworking.org/trellis/

You may find some useful information to set up an environment at: https://docs.trellisfabric.org/quickstart.html
